import type { LinkedInLearningAsset } from '@/app/lib/linkedin/types';

export const khanAcademyCourses: LinkedInLearningAsset[] = [
  // ── Computer Science & Programming ───────────────────────────────────────
  {
    urn: 'urn:ka:algorithms',
    title: 'Algorithms',
    description:
      'Explore fundamental algorithms including sorting, searching, and graph traversal. Learn how to analyse algorithm efficiency using Big-O notation and apply these concepts to real problems.',
    url: 'https://www.khanacademy.org/computing/computer-science/algorithms',
    imageUrl: null,
    durationInSeconds: 14400,
    durationFormatted: '4h',
    skillLevel: 'INTERMEDIATE',
    releasedAt: null,
    topics: ['Algorithms', 'Computer Science', 'Data Structures'],
    authors: [{ name: 'Khan Academy' }],
    contentType: 'COURSE',
  },
  {
    urn: 'urn:ka:programming',
    title: 'Intro to Programming',
    description:
      'Get started with programming using JavaScript and ProcessingJS. Build interactive drawings, animations, and simulations while mastering variables, loops, and functions.',
    url: 'https://www.khanacademy.org/computing/computer-programming/programming',
    imageUrl: null,
    durationInSeconds: 18000,
    durationFormatted: '5h',
    skillLevel: 'BEGINNER',
    releasedAt: null,
    topics: ['Programming', 'JavaScript', 'Beginners'],
    authors: [{ name: 'Khan Academy' }],
    contentType: 'COURSE',
  },
  {
    urn: 'urn:ka:ap-computer-science-principles',
    title: 'AP Computer Science Principles',
    description:
      'A broad introduction to computing covering the internet, data, algorithms, programming, and the societal impacts of technology. Ideal preparation for the AP CS Principles exam.',
    url: 'https://www.khanacademy.org/computing/ap-computer-science-principles',
    imageUrl: null,
    durationInSeconds: 28800,
    durationFormatted: '8h',
    skillLevel: 'BEGINNER',
    releasedAt: null,
    topics: ['Computer Science', 'AP Courses', 'Programming'],
    authors: [{ name: 'Khan Academy' }],
    contentType: 'COURSE',
  },
  {
    urn: 'urn:ka:html-css',
    title: 'HTML/CSS: Making webpages',
    description:
      'Learn to create and style web pages using HTML and CSS from scratch. Covers document structure, selectors, layouts, and responsive design principles.',
    url: 'https://www.khanacademy.org/computing/computer-programming/html-css',
    imageUrl: null,
    durationInSeconds: 21600,
    durationFormatted: '6h',
    skillLevel: 'BEGINNER',
    releasedAt: null,
    topics: ['Web Development', 'HTML', 'CSS'],
    authors: [{ name: 'Khan Academy' }],
    contentType: 'COURSE',
  },
  {
    urn: 'urn:ka:sql',
    title: 'Intro to SQL: Querying and managing data',
    description:
      'Master SQL fundamentals including creating tables, inserting data, and writing queries to retrieve and aggregate information. Covers joins, subqueries, and database design basics.',
    url: 'https://www.khanacademy.org/computing/computer-programming/sql',
    imageUrl: null,
    durationInSeconds: 10800,
    durationFormatted: '3h',
    skillLevel: 'BEGINNER',
    releasedAt: null,
    topics: ['SQL', 'Databases', 'Programming'],
    authors: [{ name: 'Khan Academy' }],
    contentType: 'COURSE',
  },
  {
    urn: 'urn:ka:cryptography',
    title: 'Cryptography',
    description:
      'Understand the mathematics and algorithms behind modern cryptography. Topics include Caesar ciphers, modular arithmetic, RSA encryption, and how HTTPS secures web traffic.',
    url: 'https://www.khanacademy.org/computing/computer-science/cryptography',
    imageUrl: null,
    durationInSeconds: 12600,
    durationFormatted: '3.5h',
    skillLevel: 'INTERMEDIATE',
    releasedAt: null,
    topics: ['Cryptography', 'Computer Science', 'Security'],
    authors: [{ name: 'Khan Academy' }],
    contentType: 'COURSE',
  },

  // ── Mathematics ──────────────────────────────────────────────────────────
  {
    urn: 'urn:ka:statistics-probability',
    title: 'Statistics & Probability',
    description:
      'Develop a solid understanding of descriptive statistics, probability distributions, and inferential statistics. Learn how to analyse data, interpret results, and apply statistical thinking.',
    url: 'https://www.khanacademy.org/math/statistics-probability',
    imageUrl: null,
    durationInSeconds: 36000,
    durationFormatted: '10h',
    skillLevel: 'INTERMEDIATE',
    releasedAt: null,
    topics: ['Statistics', 'Probability', 'Mathematics'],
    authors: [{ name: 'Khan Academy' }],
    contentType: 'COURSE',
  },
  {
    urn: 'urn:ka:calculus-1',
    title: 'Calculus 1',
    description:
      'Build a strong foundation in differential calculus, including limits, derivatives, and their applications. Develop problem-solving skills used in engineering, physics, and economics.',
    url: 'https://www.khanacademy.org/math/calculus-1',
    imageUrl: null,
    durationInSeconds: 43200,
    durationFormatted: '12h',
    skillLevel: 'INTERMEDIATE',
    releasedAt: null,
    topics: ['Calculus', 'Mathematics', 'Derivatives'],
    authors: [{ name: 'Khan Academy' }],
    contentType: 'COURSE',
  },
  {
    urn: 'urn:ka:linear-algebra',
    title: 'Linear Algebra',
    description:
      'Explore vectors, matrices, transformations, and eigenvalues with intuitive visual explanations. This course builds the mathematical backbone required for machine learning and computer graphics.',
    url: 'https://www.khanacademy.org/math/linear-algebra',
    imageUrl: null,
    durationInSeconds: 32400,
    durationFormatted: '9h',
    skillLevel: 'ADVANCED',
    releasedAt: null,
    topics: ['Linear Algebra', 'Mathematics', 'Matrices'],
    authors: [{ name: 'Khan Academy' }],
    contentType: 'COURSE',
  },
  {
    urn: 'urn:ka:precalculus',
    title: 'Precalculus',
    description:
      'Bridge the gap between algebra and calculus with thorough coverage of functions, trigonometry, and analytic geometry. Essential preparation for any calculus or university-level maths course.',
    url: 'https://www.khanacademy.org/math/precalculus',
    imageUrl: null,
    durationInSeconds: 39600,
    durationFormatted: '11h',
    skillLevel: 'BEGINNER',
    releasedAt: null,
    topics: ['Precalculus', 'Mathematics', 'Trigonometry'],
    authors: [{ name: 'Khan Academy' }],
    contentType: 'COURSE',
  },
  {
    urn: 'urn:ka:differential-equations',
    title: 'Differential Equations',
    description:
      'Solve ordinary differential equations using analytical techniques and understand their applications in physics, biology, and engineering. Covers first and second-order ODEs, and Laplace transforms.',
    url: 'https://www.khanacademy.org/math/differential-equations',
    imageUrl: null,
    durationInSeconds: 28800,
    durationFormatted: '8h',
    skillLevel: 'ADVANCED',
    releasedAt: null,
    topics: ['Differential Equations', 'Mathematics', 'Calculus'],
    authors: [{ name: 'Khan Academy' }],
    contentType: 'COURSE',
  },
  {
    urn: 'urn:ka:ap-statistics',
    title: 'AP Statistics',
    description:
      'Prepare for the AP Statistics exam with comprehensive coverage of data collection, exploratory analysis, probability, and statistical inference. Includes worked examples and practice problems.',
    url: 'https://www.khanacademy.org/math/ap-statistics',
    imageUrl: null,
    durationInSeconds: 46800,
    durationFormatted: '13h',
    skillLevel: 'INTERMEDIATE',
    releasedAt: null,
    topics: ['Statistics', 'AP Courses', 'Mathematics'],
    authors: [{ name: 'Khan Academy' }],
    contentType: 'COURSE',
  },

  // ── Science ──────────────────────────────────────────────────────────────
  {
    urn: 'urn:ka:ap-biology',
    title: 'AP Biology',
    description:
      'Dive into cellular biology, genetics, evolution, and ecology at an advanced level. This comprehensive course prepares students for the AP Biology exam and college-level study.',
    url: 'https://www.khanacademy.org/science/ap-biology',
    imageUrl: null,
    durationInSeconds: 54000,
    durationFormatted: '15h',
    skillLevel: 'ADVANCED',
    releasedAt: null,
    topics: ['Biology', 'AP Courses', 'Science'],
    authors: [{ name: 'Khan Academy' }],
    contentType: 'COURSE',
  },
  {
    urn: 'urn:ka:ap-chemistry',
    title: 'AP Chemistry',
    description:
      'Master atomic structure, bonding, thermodynamics, kinetics, and electrochemistry. Rigorous content aligned to the AP Chemistry curriculum with detailed worked examples.',
    url: 'https://www.khanacademy.org/science/ap-chemistry-beta',
    imageUrl: null,
    durationInSeconds: 57600,
    durationFormatted: '16h',
    skillLevel: 'ADVANCED',
    releasedAt: null,
    topics: ['Chemistry', 'AP Courses', 'Science'],
    authors: [{ name: 'Khan Academy' }],
    contentType: 'COURSE',
  },
  {
    urn: 'urn:ka:ap-physics-1',
    title: 'AP Physics 1',
    description:
      'Explore Newtonian mechanics, waves, electricity, and simple circuits with a focus on conceptual understanding and quantitative problem-solving. Aligned to the College Board AP Physics 1 framework.',
    url: 'https://www.khanacademy.org/science/ap-physics-1',
    imageUrl: null,
    durationInSeconds: 50400,
    durationFormatted: '14h',
    skillLevel: 'INTERMEDIATE',
    releasedAt: null,
    topics: ['Physics', 'AP Courses', 'Science'],
    authors: [{ name: 'Khan Academy' }],
    contentType: 'COURSE',
  },
  {
    urn: 'urn:ka:organic-chemistry',
    title: 'Organic Chemistry',
    description:
      'Learn the principles of organic chemistry including functional groups, reaction mechanisms, stereochemistry, and spectroscopy. Designed for university students and pre-med learners.',
    url: 'https://www.khanacademy.org/science/organic-chemistry',
    imageUrl: null,
    durationInSeconds: 43200,
    durationFormatted: '12h',
    skillLevel: 'ADVANCED',
    releasedAt: null,
    topics: ['Organic Chemistry', 'Chemistry', 'Science'],
    authors: [{ name: 'Khan Academy' }],
    contentType: 'COURSE',
  },
  {
    urn: 'urn:ka:physics',
    title: 'Physics',
    description:
      'Build an intuitive understanding of classical physics from motion and forces to waves and electromagnetism. Ideal for high school students or anyone refreshing their physics fundamentals.',
    url: 'https://www.khanacademy.org/science/physics',
    imageUrl: null,
    durationInSeconds: 36000,
    durationFormatted: '10h',
    skillLevel: 'BEGINNER',
    releasedAt: null,
    topics: ['Physics', 'Science', 'Mechanics'],
    authors: [{ name: 'Khan Academy' }],
    contentType: 'COURSE',
  },

  // ── Humanities ───────────────────────────────────────────────────────────
  {
    urn: 'urn:ka:world-history',
    title: 'World History',
    description:
      'Journey through human history from the origins of civilisation to the modern era. Covers major empires, revolutions, trade networks, and the forces that shaped today\'s world.',
    url: 'https://www.khanacademy.org/humanities/world-history',
    imageUrl: null,
    durationInSeconds: 36000,
    durationFormatted: '10h',
    skillLevel: 'BEGINNER',
    releasedAt: null,
    topics: ['History', 'Humanities', 'World History'],
    authors: [{ name: 'Khan Academy' }],
    contentType: 'COURSE',
  },
  {
    urn: 'urn:ka:art-history',
    title: 'Art History',
    description:
      'Survey art from prehistory to the contemporary period through close visual analysis and cultural context. Ideal for students studying design, history, or cultural studies.',
    url: 'https://www.khanacademy.org/humanities/art-history',
    imageUrl: null,
    durationInSeconds: 28800,
    durationFormatted: '8h',
    skillLevel: 'BEGINNER',
    releasedAt: null,
    topics: ['Art History', 'Humanities', 'Culture'],
    authors: [{ name: 'Khan Academy' }],
    contentType: 'COURSE',
  },
  {
    urn: 'urn:ka:grammar',
    title: 'Grammar',
    description:
      'Strengthen your command of English grammar through clear explanations and practice exercises covering parts of speech, sentence structure, punctuation, and usage.',
    url: 'https://www.khanacademy.org/humanities/grammar',
    imageUrl: null,
    durationInSeconds: 18000,
    durationFormatted: '5h',
    skillLevel: 'BEGINNER',
    releasedAt: null,
    topics: ['Grammar', 'Writing', 'English'],
    authors: [{ name: 'Khan Academy' }],
    contentType: 'COURSE',
  },
  {
    urn: 'urn:ka:us-history',
    title: 'US History',
    description:
      'Trace American history from early colonisation through to contemporary issues. Covers key political, social, and economic developments that defined the United States.',
    url: 'https://www.khanacademy.org/humanities/us-history',
    imageUrl: null,
    durationInSeconds: 39600,
    durationFormatted: '11h',
    skillLevel: 'BEGINNER',
    releasedAt: null,
    topics: ['US History', 'History', 'Humanities'],
    authors: [{ name: 'Khan Academy' }],
    contentType: 'COURSE',
  },

  // ── Economics & Finance ──────────────────────────────────────────────────
  {
    urn: 'urn:ka:microeconomics',
    title: 'Microeconomics',
    description:
      'Analyse consumer and firm behaviour, market structures, and price theory. Covers supply and demand, elasticity, market failures, and game theory fundamentals.',
    url: 'https://www.khanacademy.org/economics-finance-domain/microeconomics',
    imageUrl: null,
    durationInSeconds: 25200,
    durationFormatted: '7h',
    skillLevel: 'INTERMEDIATE',
    releasedAt: null,
    topics: ['Microeconomics', 'Economics', 'Finance'],
    authors: [{ name: 'Khan Academy' }],
    contentType: 'COURSE',
  },
  {
    urn: 'urn:ka:macroeconomics',
    title: 'Macroeconomics',
    description:
      'Understand how national economies work, including GDP, inflation, unemployment, monetary policy, and fiscal policy. Covers Keynesian and classical frameworks for analysing economic cycles.',
    url: 'https://www.khanacademy.org/economics-finance-domain/macroeconomics',
    imageUrl: null,
    durationInSeconds: 25200,
    durationFormatted: '7h',
    skillLevel: 'INTERMEDIATE',
    releasedAt: null,
    topics: ['Macroeconomics', 'Economics', 'Finance'],
    authors: [{ name: 'Khan Academy' }],
    contentType: 'COURSE',
  },
  {
    urn: 'urn:ka:core-finance',
    title: 'Finance & Capital Markets',
    description:
      'Learn personal finance essentials and capital markets concepts including interest, compound growth, stocks, bonds, and investment fundamentals. No prior finance knowledge required.',
    url: 'https://www.khanacademy.org/economics-finance-domain/core-finance',
    imageUrl: null,
    durationInSeconds: 21600,
    durationFormatted: '6h',
    skillLevel: 'BEGINNER',
    releasedAt: null,
    topics: ['Finance', 'Investing', 'Economics'],
    authors: [{ name: 'Khan Academy' }],
    contentType: 'COURSE',
  },
  {
    urn: 'urn:ka:ap-macroeconomics',
    title: 'AP Macroeconomics',
    description:
      'Prepare for the AP Macroeconomics exam with coverage of national income accounting, economic growth, monetary systems, and international trade. Includes practice exam questions.',
    url: 'https://www.khanacademy.org/economics-finance-domain/ap-macroeconomics',
    imageUrl: null,
    durationInSeconds: 32400,
    durationFormatted: '9h',
    skillLevel: 'INTERMEDIATE',
    releasedAt: null,
    topics: ['Macroeconomics', 'AP Courses', 'Economics'],
    authors: [{ name: 'Khan Academy' }],
    contentType: 'COURSE',
  },
];
